sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "pypy3"
jobs:
  include:
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
install:
  - pip3 install --upgrade pip flake8 codecov
  - pip3 install -r requirements.txt
before_script:
  - git -c core.whitespace="tab-in-indent,tabwidth=4"
      diff --check $(git merge-base master HEAD)
  - flake8 scapy_unroot tests
script:
  - coverage run ./setup.py test
after_success:
  - codecov
